services:
  mailpit:
    container_name: mailhog
    image: axllent/mailpit:${MAGEFLEET_MAILPIT_VERSION:-latest}
    environment:
      - MP_DATABASE=/data/mailpit.db
    volumes:
      - mailpitdata:/data
    labels:
      traefik.enable: true
      traefik.http.routers.mailpit.tls: true
      traefik.http.routers.mailpit.priority: 2
      traefik.http.routers.mailpit.rule: Host(`webmail.${MAGEFLEET_SERVICE_DOMAIN:-magefleet.test}`)
      traefik.http.routers.mailpit.service: mailpit
      traefik.http.services.mailpit.loadbalancer.server.port: 8025
      # Legacy Mailhog redirect
      traefik.http.routers.legacy-mailhog.tls: true
      traefik.http.routers.legacy-mailhog.priority: 1
      traefik.http.routers.legacy-mailhog.rule: Host(`mailhog.${MAGEFLEET_SERVICE_DOMAIN:-magefleet.test}`)
      traefik.http.routers.legacy-mailhog.middlewares: legacy-mailhog-redirect
      traefik.http.middlewares.legacy-mailhog-redirect.redirectregex.regex: "^https?://mailhog\\.([^/]+)/.*"
      traefik.http.middlewares.legacy-mailhog-redirect.redirectregex.replacement: https://webmail.$${1}/
      traefik.http.middlewares.legacy-mailhog-redirect.redirectregex.permanent: true

    restart: ${MAGEFLEET_RESTART_POLICY:-always}
volumes:
  mailpitdata: